apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service  # Nama dari Service
  labels:
    app: karsajobs  # Label aplikasi
spec:
  type: NodePort  # Jenis Service yang digunakan (NodePort)
  selector:
    app: karsajobs  # Seleksi pod dengan label aplikasi
    tier: backend  # Seleksi pod dengan label tier
  ports:
  - port: 8080  # Port yang akan di-expose oleh Service
    targetPort: 8080  # Port target yang diarahkan ke pod
    nodePort: 31234  # Port di node host yang dapat diakses untuk layanan
