apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service  # Nama dari Service
  labels:
    app: karsajobs  # Label aplikasi
spec:
  selector:
    app: karsajobs  # Seleksi pod dengan label aplikasi
    tier: frontend  # Seleksi pod dengan label tier
  ports:
  - port: 8000  # Port yang akan di-expose oleh Service
  type: NodePort  # Jenis Service yang digunakan (NodePort)
